### ISSUE TITLE
Follow your own docker-compose.yml conventions consistently

### ISSUE THREAD

**Issue by hagenhaus** [reach-sh/reach-lang#173]
`reach scaffold` generates a `docker-compose.yml` file that contains inconsistencies regarding naming and ordering conventions that had been established prior to the addition of Conflux. Whether you stick to the old conventions or change to new ones, I recommend that you choose and follow your own conventions in order to help developers understand this file quickly. Here are examples:

**Current Convention**: `name-devnet`.

Examples: `ethereum-devnet` and `algorand-devnet`.

Non-adherence: `devnet-cfx`.

**Current Convention**: List `live` first and then `dockerized`.

Examples:

```
reach-app-seller-and-buyer-ETH-live
reach-app-seller-and-buyer-ETH-test-dockerized-geth

reach-app-seller-and-buyer-ALGO-live
reach-app-seller-and-buyer-ALGO-test-dockerized-algod
```

Non-adherence: 

```
reach-app-seller-and-buyer-CFX-devnet
reach-app-seller-and-buyer-CFX-live
```

**Current Convention**: Indicate `devnet` with `test-dockerized`. 

Examples:

```
reach-app-seller-and-buyer-ETH-test-dockerized-geth
reach-app-seller-and-buyer-ALGO-test-dockerized-algod
```

Non-adherence: `reach-app-seller-and-buyer-CFX-devnet`.

**Current Convention**:  Service order is Ethereum, Algorand.

Example:

```
ethereum-devnet:
    image: reachsh/ethereum-devnet:0.1
algorand-devnet:
    image: reachsh/algorand-devnet:0.1

reach-app-seller-and-buyer-ETH-live:
    ...
reach-app-seller-and-buyer-ALGO-live:
    ...
```

Non-adherence: The Conflux entries are inconsistent. The image entry appears before ethereum and algorand. The environment entry appears after ethereum and algorand.
